version: "3"
services:
  app:
    build: .
    tty: true
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./Gemfile:/drover-api/Gemfile
      - ./Gemfile.lock:/drover-api/Gemfile.lock
